version: "3.9"

services:
  test-mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_VERSION:-2019-latest}
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      TZ: UTC
      SA_PASSWORD: A_Str0ng_Required_Password
  test-mssql-initdb:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - "test-mssql"
    command: [ "sh", "/opt/mssql-tools/bin/initdb.sh","test-mssql,1433","A_Str0ng_Required_Password","/opt/data/init.sql" ]
    volumes:
      - type: bind
        source: ./initdb.sh
        target: /opt/mssql-tools/bin/initdb.sh
        read_only: true
      - type: bind
        source: ../src/test/resources/init.sql
        target: /opt/data/init.sql
        read_only: true
