version: "3"

services:
  test-mysql:
    image: mysql:5.7
#    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testschema
    command: --max_allowed_packet=33554432 --max_prepared_stmt_count=16382 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ../../src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
