/*
 *
 *  Copyright (c) 2021 Vladimir Vishnevskii
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Eclipse Public License 2.0 which is available at
 *  http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
 *  which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 *  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 *
 */

package io.vertx.clickhouseclient.binary.alltypes;

import io.vertx.clickhouseclient.binary.impl.codec.columns.DateColumnReader;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.sqlclient.Row;
import io.vertx.sqlclient.Tuple;
import org.junit.runner.RunWith;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

@RunWith(VertxUnitRunner.class)
public class DateTest extends AllTypesBase<LocalDate> {
  public DateTest() {
    super("date", new MyColumnChecker<>(LocalDate.class, Tuple::getLocalDate, Row::getLocalDate, Tuple::getArrayOfLocalDates, Row::getArrayOfLocalDates));
  }

  @Override
  public List<Tuple> createBatch() {
    LocalDate v1 = LocalDate.of(2020, 3, 29);
    LocalDate v2 = v1.plusDays(2);
    LocalDate v3 = v2.plusDays(3);
    LocalDate v4 = v1.minusDays(2);
    LocalDate v5 = v2.minusDays(3);
    LocalDate v6 = v2.minusDays(4);
    LocalDate nv = DateColumnReader.MIN_VALUE;
    LocalDate mn = DateColumnReader.MIN_VALUE;
    LocalDate mx = DateColumnReader.MAX_VALUE;

    return Arrays.asList(
      //            id    simple_t    nullable_t   array_t                                              array3_t                                                                                                                nullable_array_t                                        nullable_array3_t                                                                                        simple_lc_t  nullable_lc_t   array_lc_t                                        array3_lc_t                                                                                                      nullable_array_lc_t                                      nullable_array3_lc_t
      Tuple.of((byte)1,        mn,      mn,        new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mn, mn},                                   new LocalDate[][][]{{{mn, null, mn}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},           mn,        mn,      new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mn, mn},                                    new LocalDate[][][]{{{mn, null, mn}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}            ),
      Tuple.of((byte)2,        mn,      mn,        new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mn, mn},                                   new LocalDate[][][]{{{mn, null, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},     mn,        mn,      new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mn, mn},                                    new LocalDate[][][]{{{mn, null, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}      ),
      Tuple.of((byte)3,        mn,      mn,        new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mn, null, mn},                             new LocalDate[][][]{{{mn, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},           mn,        mn,      new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mn, null, mn},                              new LocalDate[][][]{{{mn, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}            ),
      Tuple.of((byte)4,        mn,      mn,        new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mn, null, mn},                             new LocalDate[][][]{{{mn, null, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},                     mn,        mn,      new LocalDate[]{mn, mn},                             new LocalDate[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mn, null, mn},                              new LocalDate[][][]{{{mn, null, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}                      ),
      Tuple.of((byte)5,        mx,      mx,        new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mx, mx},                                   new LocalDate[][][]{{{mx, null, mx}, {mx, mx, null}, {}}, {{mn, mn}, {mn, null, mn}, {}}, {{}, {null}, {}}},         mx,        mx,      new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mx, null, mx},                              new LocalDate[][][]{{{mx, null, mx}, {mx, mx, null}, {}}, {{mn, mn}, {mn, null, mn}, {}}, {{}, {null}, {}}}          ),
      Tuple.of((byte)6,        mn,      mn,        new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mx, mx},                                   new LocalDate[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{null}, {}, {}}},                     mn,        mn,      new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mx, null, mx},                              new LocalDate[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{null}, {}, {}}}                      ),
      Tuple.of((byte)7,        mx,      mx,        new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mx, null, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         mx,        mx,      new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mx, null, mx},                              new LocalDate[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                          ),
      Tuple.of((byte)8,        mn,      mn,        new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mx, null, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, null, mx, null}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},               mn,        mn,      new LocalDate[]{mx, mx},                             new LocalDate[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mx, null, mx},                              new LocalDate[][][]{{{mx, mx}, {mx, null, mx, null}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}                ),
      Tuple.of((byte)9,        mx,      mx,        new LocalDate[]{mn, mx},                             new LocalDate[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mn, null, mx},                             new LocalDate[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                   mx,        mx,      new LocalDate[]{mn, mx},                             new LocalDate[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mn, null, mx},                              new LocalDate[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                    ),
      Tuple.of((byte)10,       mn,      mn,        new LocalDate[]{mn, mx},                             new LocalDate[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{mn, null, mx},                             new LocalDate[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                   mn,        mn,      new LocalDate[]{mn, mx},                             new LocalDate[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{mn, null, mx},                              new LocalDate[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                    ),
      Tuple.of((byte)11,       v2,      v3,        new LocalDate[]{},                                   new LocalDate[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                                 new LocalDate[]{},                                         new LocalDate[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}},                                                       v2,        v3,      new LocalDate[]{},                                   new LocalDate[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                          new LocalDate[]{},                                          new LocalDate[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}}                                                        ),
      Tuple.of((byte)12,       v2,      v3,        new LocalDate[]{},                                   new LocalDate[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                                 new LocalDate[]{},                                         new LocalDate[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}},                                                       v2,        v3,      new LocalDate[]{},                                   new LocalDate[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                          new LocalDate[]{},                                          new LocalDate[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}}                                                        ),
      Tuple.of((byte)13,       v2,      v3,        new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                                 new LocalDate[]{},                                         new LocalDate[][][]{{{}}},                                                                                           v2,        v3,      new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                          new LocalDate[]{},                                          new LocalDate[][][]{{{}}}                                                                                            ),
      Tuple.of((byte)14,       v2,      v3,        new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                                 new LocalDate[]{},                                         new LocalDate[][][]{{{}}},                                                                                           v2,        v3,      new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                          new LocalDate[]{},                                          new LocalDate[][][]{{{}}}                                                                                            ),
      Tuple.of((byte)15,       v2,      v3,        new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                                 new LocalDate[]{null},                                     new LocalDate[][][]{{{null}}},                                                                                       v2,        v3,      new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                          new LocalDate[]{null},                                      new LocalDate[][][]{{{null}}}                                                                                            ),
      Tuple.of((byte)16,       v2,      v3,        new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                                 new LocalDate[]{null},                                     new LocalDate[][][]{{{null}}},                                                                                       v2,        v3,      new LocalDate[]{},                                   new LocalDate[][][]{{{}}},                                                                                          new LocalDate[]{null},                                      new LocalDate[][][]{{{null}}}                                                                                            ),
      Tuple.of((byte)17,       v2,      v3,        new LocalDate[]{nv},                                 new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{nv},                                       new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                               v2,        v3,      new LocalDate[]{nv},                                 new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{nv},                                        new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                                ),
      Tuple.of((byte)18,       v2,      v3,        new LocalDate[]{nv},                                 new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new LocalDate[]{nv},                                       new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                               v2,        v3,      new LocalDate[]{nv},                                 new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new LocalDate[]{nv},                                        new LocalDate[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                                ),
      Tuple.of((byte)19,       v2,      v3,        new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         new LocalDate[]{nv, mn, null, mx},                         new LocalDate[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}},       v2,        v3,      new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                  new LocalDate[]{nv},                                        new LocalDate[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}}        ),
      Tuple.of((byte)20,       v2,      v3,        new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         new LocalDate[]{nv, mn, null, mx},                         new LocalDate[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}},       v2,        v3,      new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                  new LocalDate[]{nv},                                        new LocalDate[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}}        ),
      Tuple.of((byte)21,       v2,      v3,        new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{nv, mn, null, mx},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v2,        v3,      new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{nv, mn, null, mx},                          new LocalDate[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)22,       v2,      v3,        new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{nv, mn, null, mx},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, null, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v2,        v3,      new LocalDate[]{nv, mn, mx},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{nv, mn, null, mx},                          new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, null, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)23, nv,    null,        new LocalDate[]{v3, v1, nv, mx, v4},                 new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{v3, v1, null, nv, mx, v3},                 new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5, null}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,      null,      new LocalDate[]{v3, v1, nv, mx, v4},                 new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{nv, v2, null, v3, v2},                       new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5, null}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}} ),
      Tuple.of((byte)24, nv,    null,        new LocalDate[]{v3, v1, nv, mx, v4},                 new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{v3, v1, null, nv, mx, v3},                 new LocalDate[][][]{{{nv, mn, mx, null, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,      null,      new LocalDate[]{v3, v1, nv, mx, v4},                 new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{nv, v2, null, v3, v2},                       new LocalDate[][][]{{{nv, mn, mx, null, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}} ),
      Tuple.of((byte)25,       v1,      v1,        new LocalDate[]{v1, nv, nv},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{v3, nv, null},                             new LocalDate[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v1,        v1,      new LocalDate[]{v1, nv, nv},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{v2, nv, null},                              new LocalDate[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)26,       nv,      nv,        new LocalDate[]{nv, nv, nv},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{nv, null, v4},                             new LocalDate[][][]{{{nv, null, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,        nv,      new LocalDate[]{nv, nv, nv},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{nv, null, nv},                              new LocalDate[][][]{{{nv, null, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)27,       v6,      v5,        new LocalDate[]{v4, nv, nv},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{v3, nv, null},                             new LocalDate[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new LocalDate[]{v4, nv, nv},                         new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{v2, nv, null},                              new LocalDate[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)28,       v6,      v5,        new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null}, new LocalDate[][][]{{{nv, mn, mx, v1, null, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null},  new LocalDate[][][]{{{nv, mn, mx, v1, null, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)29,       v6,      v5,        new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null}, new LocalDate[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new LocalDate[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new LocalDate[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null},  new LocalDate[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  )
    );
  }
}
