/*
 *
 *  Copyright (c) 2021 Vladimir Vishnevskii
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Eclipse Public License 2.0 which is available at
 *  http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
 *  which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 *  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 *
 */

package io.vertx.clickhouseclient.binary.alltypes;

import io.vertx.clickhouseclient.binary.impl.codec.columns.IPv4Column;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.sqlclient.Tuple;
import org.junit.runner.RunWith;

import java.net.Inet4Address;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.List;

@RunWith(VertxUnitRunner.class)
public class IPv4Test extends AllTypesBase<Inet4Address> {
  public IPv4Test() {
    super("ipv4", new MyColumnChecker<>(Inet4Address.class, null, null, null, null));
  }

  private static Inet4Address ipv4(int b1, int b2, int b3, int b4) {
    try {
      return (Inet4Address) Inet4Address.getByAddress(new byte[]{(byte)b1, (byte)b2, (byte)b3, (byte)b4});
    } catch (UnknownHostException ex) {
      throw new RuntimeException(ex);
    }
  }

  @Override
  public List<Tuple> createBatch() {
    Inet4Address v1 = ipv4(192, 168, 1, 1);
    Inet4Address v2 = ipv4(10, 23, 1, 1);
    Inet4Address v3 = ipv4(1, 1, 1, 1);
    Inet4Address v4 = ipv4(8, 8, 8, 8);
    Inet4Address v5 = ipv4(1, 2, 3, 4);
    Inet4Address v6 = ipv4(100, 100, 100, 100);
    Inet4Address nv = IPv4Column.ZERO_VALUE;
    Inet4Address mn = IPv4Column.MIN_VALUE;
    Inet4Address mx = IPv4Column.MAX_VALUE;

    return Arrays.asList(
      //            id    simple_t    nullable_t   array_t                                           array3_t                                                                                                                nullable_array_t                                        nullable_array3_t                                                                                        simple_lc_t  nullable_lc_t   array_lc_t                                        array3_lc_t                                                                                                      nullable_array_lc_t                                      nullable_array3_lc_t
      Tuple.of((byte)1,        mn,      mn,        new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mn, mn},                                   new Inet4Address[][][]{{{mn, null, mn}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},           mn,        mn,      new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mn, mn},                                    new Inet4Address[][][]{{{mn, null, mn}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}            ),
      Tuple.of((byte)2,        mn,      mn,        new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mn, mn},                                   new Inet4Address[][][]{{{mn, null, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},     mn,        mn,      new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mn, mn},                                    new Inet4Address[][][]{{{mn, null, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}      ),
      Tuple.of((byte)3,        mn,      mn,        new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mn, null, mn},                             new Inet4Address[][][]{{{mn, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},           mn,        mn,      new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mn, null, mn},                              new Inet4Address[][][]{{{mn, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}            ),
      Tuple.of((byte)4,        mn,      mn,        new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mn, null, mn},                             new Inet4Address[][][]{{{mn, null, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},                     mn,        mn,      new Inet4Address[]{mn, mn},                             new Inet4Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mn, null, mn},                              new Inet4Address[][][]{{{mn, null, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}                      ),
      Tuple.of((byte)5,        mx,      mx,        new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mx, mx},                                   new Inet4Address[][][]{{{mx, null, mx}, {mx, mx, null}, {}}, {{mn, mn}, {mn, null, mn}, {}}, {{}, {null}, {}}},         mx,        mx,      new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mx, null, mx},                              new Inet4Address[][][]{{{mx, null, mx}, {mx, mx, null}, {}}, {{mn, mn}, {mn, null, mn}, {}}, {{}, {null}, {}}}          ),
      Tuple.of((byte)6,        mn,      mn,        new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mx, mx},                                   new Inet4Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{null}, {}, {}}},                     mn,        mn,      new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mx, null, mx},                              new Inet4Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{null}, {}, {}}}                      ),
      Tuple.of((byte)7,        mx,      mx,        new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mx, null, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         mx,        mx,      new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mx, null, mx},                              new Inet4Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                          ),
      Tuple.of((byte)8,        mn,      mn,        new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mx, null, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, null, mx, null}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},               mn,        mn,      new Inet4Address[]{mx, mx},                             new Inet4Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mx, null, mx},                              new Inet4Address[][][]{{{mx, mx}, {mx, null, mx, null}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}                ),
      Tuple.of((byte)9,        mx,      mx,        new Inet4Address[]{mn, mx},                             new Inet4Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mn, null, mx},                             new Inet4Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                   mx,        mx,      new Inet4Address[]{mn, mx},                             new Inet4Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mn, null, mx},                              new Inet4Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                    ),
      Tuple.of((byte)10,       mn,      mn,        new Inet4Address[]{mn, mx},                             new Inet4Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{mn, null, mx},                             new Inet4Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                   mn,        mn,      new Inet4Address[]{mn, mx},                             new Inet4Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{mn, null, mx},                              new Inet4Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                    ),
      Tuple.of((byte)11,       v2,      v3,        new Inet4Address[]{},                                   new Inet4Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                                 new Inet4Address[]{},                                         new Inet4Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}},                                                       v2,        v3,      new Inet4Address[]{},                                   new Inet4Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                          new Inet4Address[]{},                                          new Inet4Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}}                                                        ),
      Tuple.of((byte)12,       v2,      v3,        new Inet4Address[]{},                                   new Inet4Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                                 new Inet4Address[]{},                                         new Inet4Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}},                                                       v2,        v3,      new Inet4Address[]{},                                   new Inet4Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                          new Inet4Address[]{},                                          new Inet4Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}}                                                        ),
      Tuple.of((byte)13,       v2,      v3,        new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                                 new Inet4Address[]{},                                         new Inet4Address[][][]{{{}}},                                                                                           v2,        v3,      new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                          new Inet4Address[]{},                                          new Inet4Address[][][]{{{}}}                                                                                            ),
      Tuple.of((byte)14,       v2,      v3,        new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                                 new Inet4Address[]{},                                         new Inet4Address[][][]{{{}}},                                                                                           v2,        v3,      new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                          new Inet4Address[]{},                                          new Inet4Address[][][]{{{}}}                                                                                            ),
      Tuple.of((byte)15,       v2,      v3,        new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                                 new Inet4Address[]{null},                                     new Inet4Address[][][]{{{null}}},                                                                                       v2,        v3,      new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                          new Inet4Address[]{null},                                      new Inet4Address[][][]{{{null}}}                                                                                            ),
      Tuple.of((byte)16,       v2,      v3,        new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                                 new Inet4Address[]{null},                                     new Inet4Address[][][]{{{null}}},                                                                                       v2,        v3,      new Inet4Address[]{},                                   new Inet4Address[][][]{{{}}},                                                                                          new Inet4Address[]{null},                                      new Inet4Address[][][]{{{null}}}                                                                                            ),
      Tuple.of((byte)17,       v2,      v3,        new Inet4Address[]{nv},                                 new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{nv},                                       new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                               v2,        v3,      new Inet4Address[]{nv},                                 new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{nv},                                        new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                                ),
      Tuple.of((byte)18,       v2,      v3,        new Inet4Address[]{nv},                                 new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet4Address[]{nv},                                       new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                               v2,        v3,      new Inet4Address[]{nv},                                 new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet4Address[]{nv},                                        new Inet4Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                                ),
      Tuple.of((byte)19,       v2,      v3,        new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         new Inet4Address[]{nv, mn, null, mx},                         new Inet4Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}},       v2,        v3,      new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                  new Inet4Address[]{nv},                                        new Inet4Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}}        ),
      Tuple.of((byte)20,       v2,      v3,        new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         new Inet4Address[]{nv, mn, null, mx},                         new Inet4Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}},       v2,        v3,      new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                  new Inet4Address[]{nv},                                        new Inet4Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}}        ),
      Tuple.of((byte)21,       v2,      v3,        new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{nv, mn, null, mx},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v2,        v3,      new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{nv, mn, null, mx},                          new Inet4Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)22,       v2,      v3,        new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{nv, mn, null, mx},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, null, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v2,        v3,      new Inet4Address[]{nv, mn, mx},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{nv, mn, null, mx},                          new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, null, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)23, nv,    null,        new Inet4Address[]{v3, v1, nv, mx, v4},                 new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{v3, v1, null, nv, mx, v3},                 new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5, null}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,      null,      new Inet4Address[]{v3, v1, nv, mx, v4},                 new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{nv, v2, null, v3, v2},                       new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5, null}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}} ),
      Tuple.of((byte)24, nv,    null,        new Inet4Address[]{v3, v1, nv, mx, v4},                 new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{v3, v1, null, nv, mx, v3},                 new Inet4Address[][][]{{{nv, mn, mx, null, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,      null,      new Inet4Address[]{v3, v1, nv, mx, v4},                 new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{nv, v2, null, v3, v2},                       new Inet4Address[][][]{{{nv, mn, mx, null, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}} ),
      Tuple.of((byte)25,       v1,      v1,        new Inet4Address[]{v1, nv, nv},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{v3, nv, null},                             new Inet4Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v1,        v1,      new Inet4Address[]{v1, nv, nv},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{v2, nv, null},                              new Inet4Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)26,       nv,      nv,        new Inet4Address[]{nv, nv, nv},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{nv, null, v4},                             new Inet4Address[][][]{{{nv, null, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,        nv,      new Inet4Address[]{nv, nv, nv},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{nv, null, nv},                              new Inet4Address[][][]{{{nv, null, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)27,       v6,      v5,        new Inet4Address[]{v4, nv, nv},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{v3, nv, null},                             new Inet4Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new Inet4Address[]{v4, nv, nv},                         new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{v2, nv, null},                              new Inet4Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)28,       v6,      v5,        new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null}, new Inet4Address[][][]{{{nv, mn, mx, v1, null, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null},  new Inet4Address[][][]{{{nv, mn, mx, v1, null, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)29,       v6,      v5,        new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null}, new Inet4Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet4Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet4Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null},  new Inet4Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  )
    );
  }
}
