/*
 *
 *  Copyright (c) 2021 Vladimir Vishnevskii
 *
 *  This program and the accompanying materials are made available under the
 *  terms of the Eclipse Public License 2.0 which is available at
 *  http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
 *  which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 *  SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 *
 */

package io.vertx.clickhouseclient.binary.alltypes;

import io.vertx.clickhouseclient.binary.impl.codec.columns.IPv6Column;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import io.vertx.sqlclient.Tuple;
import org.junit.runner.RunWith;

import java.net.Inet6Address;
import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.List;

@RunWith(VertxUnitRunner.class)
public class IPv6Test extends AllTypesBase<Inet6Address> {
  public IPv6Test() {
    super("ipv6", new MyColumnChecker<>(Inet6Address.class, null, null, null, null));
  }

  private static Inet6Address ipv6(int b1, int b2, int b3, int b4, int b5, int b6, int b7, int b8,
                                   int b9, int b10, int b11, int b12, int b13, int b14, int b15, int b16) {
    try {
      return (Inet6Address) Inet6Address.getByAddress(new byte[]{
        (byte)b1, (byte)b2, (byte)b3, (byte)b4,
        (byte)b5, (byte)b6, (byte)b7, (byte)b8,
        (byte)b9, (byte)b10, (byte)b11, (byte)b12,
        (byte)b13, (byte)b14, (byte)b15, (byte)b16
      });
    } catch (UnknownHostException ex) {
      throw new RuntimeException(ex);
    }
  }

  @Override
  public List<Tuple> createBatch() {
    Inet6Address v1 = ipv6(192, 168, 35, 255, 44, 42, 42, 55, 78, 90, -120, 22, 10, -67, -90, -43);
    Inet6Address v2 = ipv6(14, 23, 21, 54, 76, 90, 12, 11, -43, -11, -55, 93, 43, 87, -32, -21);
    Inet6Address v3 = ipv6(32, 11, 85, 0, 14, -12, -98, 120, 43, 32, -65, 2, 41, -9, 0, 11);
    Inet6Address v4 = ipv6(11, 0, 0, 0, 14, -43, 2, 65, 32, 14, 87, 3, 11, -9, 97, 11);
    Inet6Address v5 = ipv6(11, 98, 32, 65, 11, -46, 0, 31, 99, 104, 54, 11, 11, -65, 111, 14);
    Inet6Address v6 = ipv6(10, 10, 22, 78, -43, -46, 2, 98, 99, 43, 11, 2, -11, -33, 0, 1);
    Inet6Address nv = IPv6Column.ZERO_VALUE;
    Inet6Address mn = IPv6Column.MIN_VALUE;
    Inet6Address mx = IPv6Column.MAX_VALUE;

    return Arrays.asList(
      //            id    simple_t    nullable_t   array_t                                           array3_t                                                                                                                nullable_array_t                                        nullable_array3_t                                                                                        simple_lc_t  nullable_lc_t   array_lc_t                                        array3_lc_t                                                                                                      nullable_array_lc_t                                      nullable_array3_lc_t
      Tuple.of((byte)1,        mn,      mn,        new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mn, mn},                                   new Inet6Address[][][]{{{mn, null, mn}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},           mn,        mn,      new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mn, mn},                                    new Inet6Address[][][]{{{mn, null, mn}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}            ),
      Tuple.of((byte)2,        mn,      mn,        new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mn, mn},                                   new Inet6Address[][][]{{{mn, null, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},     mn,        mn,      new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mn, mn},                                    new Inet6Address[][][]{{{mn, null, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}      ),
      Tuple.of((byte)3,        mn,      mn,        new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mn, null, mn},                             new Inet6Address[][][]{{{mn, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},           mn,        mn,      new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mn, null, mn},                              new Inet6Address[][][]{{{mn, mn, null}, {mn, mn, null}, {null}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}            ),
      Tuple.of((byte)4,        mn,      mn,        new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mn, null, mn},                             new Inet6Address[][][]{{{mn, null, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},                     mn,        mn,      new Inet6Address[]{mn, mn},                             new Inet6Address[][][]{{{mn, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mn, null, mn},                              new Inet6Address[][][]{{{mn, null, mn}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}                      ),
      Tuple.of((byte)5,        mx,      mx,        new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mx, mx},                                   new Inet6Address[][][]{{{mx, null, mx}, {mx, mx, null}, {}}, {{mn, mn}, {mn, null, mn}, {}}, {{}, {null}, {}}},         mx,        mx,      new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mx, null, mx},                              new Inet6Address[][][]{{{mx, null, mx}, {mx, mx, null}, {}}, {{mn, mn}, {mn, null, mn}, {}}, {{}, {null}, {}}}          ),
      Tuple.of((byte)6,        mn,      mn,        new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mx, mx},                                   new Inet6Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{null}, {}, {}}},                     mn,        mn,      new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mx, null, mx},                              new Inet6Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{null}, {}, {}}}                      ),
      Tuple.of((byte)7,        mx,      mx,        new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mx, null, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         mx,        mx,      new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mx, null, mx},                              new Inet6Address[][][]{{{mx, mx}, {mx, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                          ),
      Tuple.of((byte)8,        mn,      mn,        new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mx, null, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, null, mx, null}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}},               mn,        mn,      new Inet6Address[]{mx, mx},                             new Inet6Address[][][]{{{mx, mx}, {mx, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mx, null, mx},                              new Inet6Address[][][]{{{mx, mx}, {mx, null, mx, null}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {null}, {}}}                ),
      Tuple.of((byte)9,        mx,      mx,        new Inet6Address[]{mn, mx},                             new Inet6Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mn, null, mx},                             new Inet6Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                   mx,        mx,      new Inet6Address[]{mn, mx},                             new Inet6Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mn, null, mx},                              new Inet6Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                    ),
      Tuple.of((byte)10,       mn,      mn,        new Inet6Address[]{mn, mx},                             new Inet6Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{mn, null, mx},                             new Inet6Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                   mn,        mn,      new Inet6Address[]{mn, mx},                             new Inet6Address[][][]{{{mn, mx}, {mn, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{mn, null, mx},                              new Inet6Address[][][]{{{mn, mx, null}, {mn, null, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                    ),
      Tuple.of((byte)11,       v2,      v3,        new Inet6Address[]{},                                   new Inet6Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                                 new Inet6Address[]{},                                         new Inet6Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}},                                                       v2,        v3,      new Inet6Address[]{},                                   new Inet6Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                          new Inet6Address[]{},                                          new Inet6Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}}                                                        ),
      Tuple.of((byte)12,       v2,      v3,        new Inet6Address[]{},                                   new Inet6Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                                 new Inet6Address[]{},                                         new Inet6Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}},                                                       v2,        v3,      new Inet6Address[]{},                                   new Inet6Address[][][]{{{}, {}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                          new Inet6Address[]{},                                          new Inet6Address[][][]{{{}, {}, {}}, {{}, {}, {}}, {{}, {}, {}}}                                                        ),
      Tuple.of((byte)13,       v2,      v3,        new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                                 new Inet6Address[]{},                                         new Inet6Address[][][]{{{}}},                                                                                           v2,        v3,      new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                          new Inet6Address[]{},                                          new Inet6Address[][][]{{{}}}                                                                                            ),
      Tuple.of((byte)14,       v2,      v3,        new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                                 new Inet6Address[]{},                                         new Inet6Address[][][]{{{}}},                                                                                           v2,        v3,      new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                          new Inet6Address[]{},                                          new Inet6Address[][][]{{{}}}                                                                                            ),
      Tuple.of((byte)15,       v2,      v3,        new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                                 new Inet6Address[]{null},                                     new Inet6Address[][][]{{{null}}},                                                                                       v2,        v3,      new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                          new Inet6Address[]{null},                                      new Inet6Address[][][]{{{null}}}                                                                                            ),
      Tuple.of((byte)16,       v2,      v3,        new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                                 new Inet6Address[]{null},                                     new Inet6Address[][][]{{{null}}},                                                                                       v2,        v3,      new Inet6Address[]{},                                   new Inet6Address[][][]{{{}}},                                                                                          new Inet6Address[]{null},                                      new Inet6Address[][][]{{{null}}}                                                                                            ),
      Tuple.of((byte)17,       v2,      v3,        new Inet6Address[]{nv},                                 new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{nv},                                       new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                               v2,        v3,      new Inet6Address[]{nv},                                 new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{nv},                                        new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                                ),
      Tuple.of((byte)18,       v2,      v3,        new Inet6Address[]{nv},                                 new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                                     new Inet6Address[]{nv},                                       new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                               v2,        v3,      new Inet6Address[]{nv},                                 new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                              new Inet6Address[]{nv},                                        new Inet6Address[][][]{{{nv, nv}, {nv, nv}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}                                ),
      Tuple.of((byte)19,       v2,      v3,        new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         new Inet6Address[]{nv, mn, null, mx},                         new Inet6Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}},       v2,        v3,      new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                  new Inet6Address[]{nv},                                        new Inet6Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}}        ),
      Tuple.of((byte)20,       v2,      v3,        new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                         new Inet6Address[]{nv, mn, null, mx},                         new Inet6Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}},       v2,        v3,      new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{v2, nv, mn}, {v3, mn, nv, mx}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},                  new Inet6Address[]{nv},                                        new Inet6Address[][][]{{{v2, nv, mn, null}, {v3, mn, nv, mx}, {}}, {{mn, mn, null}, {mn, mn}, {}}, {{}, {}, {}}}        ),
      Tuple.of((byte)21,       v2,      v3,        new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{nv, mn, null, mx},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v2,        v3,      new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{nv, mn, null, mx},                          new Inet6Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)22,       v2,      v3,        new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{nv, mn, null, mx},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, null, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v2,        v3,      new Inet6Address[]{nv, mn, mx},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{nv, mn, null, mx},                          new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, null, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)23, nv,    null,        new Inet6Address[]{v3, v1, nv, mx, v4},                 new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{v3, v1, null, nv, mx, v3},                 new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5, null}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,      null,      new Inet6Address[]{v3, v1, nv, mx, v4},                 new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{nv, v2, null, v3, v2},                       new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5, null}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}} ),
      Tuple.of((byte)24, nv,    null,        new Inet6Address[]{v3, v1, nv, mx, v4},                 new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{v3, v1, null, nv, mx, v3},                 new Inet6Address[][][]{{{nv, mn, mx, null, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,      null,      new Inet6Address[]{v3, v1, nv, mx, v4},                 new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{nv, v2, null, v3, v2},                       new Inet6Address[][][]{{{nv, mn, mx, null, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}} ),
      Tuple.of((byte)25,       v1,      v1,        new Inet6Address[]{v1, nv, nv},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{v3, nv, null},                             new Inet6Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v1,        v1,      new Inet6Address[]{v1, nv, nv},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{v2, nv, null},                              new Inet6Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)26,       nv,      nv,        new Inet6Address[]{nv, nv, nv},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{nv, null, v4},                             new Inet6Address[][][]{{{nv, null, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, nv,        nv,      new Inet6Address[]{nv, nv, nv},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{nv, null, nv},                              new Inet6Address[][][]{{{nv, null, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)27,       v6,      v5,        new Inet6Address[]{v4, nv, nv},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{v3, nv, null},                             new Inet6Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new Inet6Address[]{v4, nv, nv},                         new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{v2, nv, null},                              new Inet6Address[][][]{{{nv, mn, null, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)28,       v6,      v5,        new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null}, new Inet6Address[][][]{{{nv, mn, mx, v1, null, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null},  new Inet6Address[][][]{{{nv, mn, mx, v1, null, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  ),
      Tuple.of((byte)29,       v6,      v5,        new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},             new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null}, new Inet6Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}, v6,        v5,      new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6}, new Inet6Address[][][]{{{nv, mn, mx, v1, v2, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}},      new Inet6Address[]{v1, nv, mn, mx, v2, v3, v4, v5, v6, null},  new Inet6Address[][][]{{{nv, mn, mx, v1, v2, null, v3, v4, v5}, {mn, mn}, {}}, {{mn, mn}, {mn, mn}, {}}, {{}, {}, {}}}  )
    );
  }
}
