== 0.11.3

Fixed issues: https://github.com/reactiverse/reactive-pg-client/issues?q=is%3Aclosed+milestone%3A0.11.3

- Vert.x 3.7.0 upgrade

== 0.11.2

Fixed issues: https://github.com/reactiverse/reactive-pg-client/issues?q=is%3Aclosed+milestone%3A0.11.2

- Request cancellation support
- Remove @GenIgnore or use permitted-type in Tuple/Row methods
- Add documentation and an example for fetching generated keys
- Add support for sslmode

== 0.11.1

Fixed issues: https://github.com/reactiverse/reactive-pg-client/issues?q=is%3Aclosed+milestone%3A0.11.1

- Upgrade to Vert.x 3.6.2
- Generate kotlin coroutine methods
- Get details from PgException
- SSL upgradefuture failure is not properly handled

== 0.11.0

Fixed issues: https://github.com/reactiverse/reactive-pg-client/issues?q=is%3Aclosed+milestone%3A0.11.0

- Upgrade to Vert.x 3.6.0
- Example for Kotlin throws compilation errors

== 0.10.9

Fixed issues: https://github.com/reactiverse/reactive-pg-client/issues?q=is%3Aclosed+milestone%3A0.10.9

- Geometric types supports
- Accept null value for json parameter

== 0.10.8

Fixed issues: https://github.com/reactiverse/reactive-pg-client/issues?q=is%3Aclosed+milestone%3A0.10.8

- Connection pool opens more connections than necessary
- Negative numeric values are not simple queries are not properly decoded

== 0.10.7

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/14?closed=1

- Batch execution incorrectly handles batch result when the batch list is empty
- Pool connection acquisition failure is not propagated to the scheduled command
- Upgrade to Vertx 3.5.4
- Source code for rxjava and reactivex API variants missing from -sources.jar
- Allow to prepare query from a transaction object
- Rework cursor/stream documentation

== 0.10.6

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/13?closed=1

- PgPool#preparedQuery operation should always use the same connection
- Numeric type prepared statement parameters needs to be coerced

== 0.10.5

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/12?closed=1

- Connection pool queue boundary
- Pool does not handle connection failure correctly
- Rx Stream API documentation unclear

== 0.10.4

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/11?closed=1

- RowResultDecoder does not correctly decode empty text arrays
- Move to Vertx logger for warnings instead of Sysout

=== Bug fixes

- Treat unknown datatypes as text instead of binary
- Null values should always be valid in prepared statement parameters

== 0.10.3

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/10?closed=1

=== Bug fixes

- Treat unknown datatypes as text instead of binary
- Null values should always be valid in prepared statement parameters

== 0.10.2

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/9?closed=1

=== Bug fixes

- When a pooled connection is closed, the actual connection should not be made available after it has been closed internally
- Missing prepared statement tuple validation
- JSONB array treated as non array
- PreparedQuery should schedule commands from the event loop thread
- Calling Transaction rollback() leads to an NPE

== 0.10.1

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/8?closed=1

=== Bug fixes

- Connection client encoding parsing should be case insensitive for supporting Greenplum
- Use quoted identifiers in LISTEN / UNLISTEN

== 0.10.0

Fixed issues: https://github.com/reactiverse/reactive-pg-client/milestone/7?closed=1[Issues]

=== Features

- simplified transaction API
- interval data type support
- enum data type support
- cached prepared statement option
- RxJava documentation enhancements
- upgrade to Vert.x 3.5.3
- `Row` provides access to column names

=== Breaking changes

- data types in `io.reactiverse.pgclient` have been moved to `io.reactiverse.pgclient.data`
- `PgResult#updatedCount()` has been renamed to `PgResult#rowCount()`


