= Postgres Client for Eclipse Vert.x

== Using the client

To use Postgres Client for Vert.x add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>reactive-pg-client</artifactId>
  <version>0.3.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:reactive-pg-client:0.3.1-SNAPSHOT'
}
----

== Connecting to a database

You can use the client to connect to the database and interact with it.

[source,js]
----
var PgClient = require("vertx-pg-client-js/pg_client");

var client = PgClient.create(vertx, {
  "port" : 5432,
  "host" : "the-host",
  "database" : "the-db",
  "username" : "user",
  "password" : "secret"
});

client.connect(function (res, res_err) {
  if (res_err == null) {

    // Connected
    var conn = res;

    conn.createQuery("SELECT * FROM USERS").execute(function (ar, ar_err) {

      if (ar_err == null) {

        // Use result
        var result = ar;
      } else {
        console.log("It failed");
      }

      // Close the connection
      conn.close();
    });
  } else {
    console.log("Could not connect " + res_err);
  }
});

----

You can create a pool of connection to obtain a connection instead:

[source,js]
----
var PgClient = require("vertx-pg-client-js/pg_client");

var client = PgClient.create(vertx, {
  "port" : 5432,
  "host" : "the-host",
  "database" : "the-db",
  "username" : "user",
  "password" : "secret"
});

var pool = client.createPool({
  "maxSize" : 20
});

pool.getConnection(function (res, res_err) {
  if (res_err == null) {

    // Obtained a connection
    var conn = res;

    conn.createQuery("SELECT * FROM USERS").execute(function (ar, ar_err) {

      if (ar_err == null) {

        // Use result set
        var result = ar;
      } else {
        console.log("It failed");
      }

      // Return the connection to the pool
      conn.close();
    });
  } else {
    console.log("Could not obtain a connection " + res_err);
  }
});

----

When you are done with the pool, you should close it:

[source,js]
----

// Close the pool and the connection it maintains
pool.close();

----

== Prepared statements

Prepared statements can be created and managed by the application.

The `sql` string can refer to parameters by position, using $1, $2, etc...

[source,js]
----
var Tuple = require("vertx-pg-client-js/tuple");
conn.prepare("SELECT * FROM USERS WHERE user_id=$1", function (ar1, ar1_err) {

  if (ar1_err == null) {
    var preparedStatement = ar1;

    // Create a query : bind parameters
    var query = preparedStatement.createQuery(Tuple.of("julien"));

    // Execute query
    query.execute(function (ar2, ar2_err) {
      if (ar2_err == null) {

        // Get result
        var result = ar2;
      } else {
        console.log("Query failed " + ar2_err);
      }
    });
  } else {
    console.log("Could not prepare statement " + ar1_err);
  }
});

----

When you are done with the prepared statement, you should close it:

[source,js]
----
preparedStatement.close();

----

NOTE: when you close the connection, you don't need to close its prepared statements

By default the query will fetch all results, you can override this and define a maximum fetch size.

[source,js]
----
conn.prepare("SELECT * FROM USERS", function (ar1, ar1_err) {
  if (ar1_err == null) {

    var preparedStatement = ar1;

    // Create a query : bind parameters
    var query = preparedStatement.createQuery().fetch(100);

    query.execute(function (ar2, ar2_err) {

      if (ar2_err == null) {
        console.log("Got at most 100 rows");

        if (query.hasMore()) {
          // Get results
          var result = ar2;

          console.log("Get next 100");
          query.execute(function (ar3, ar3_err) {
            // Continue...
          });
        } else {
          // We are done
        }
      } else {
        console.log("Query failed " + ar2_err);
      }
    });
  } else {
    console.log("Could not prepare statement " + ar1_err);
  }
});

----

When a query is not completed you can call `link:../../jsdoc/module-vertx-pg-client-js_pg_query-PgQuery.html#close[close]` to release
the query result in progress:

[source,js]
----
conn.prepare("SELECT * FROM USERS", function (ar1, ar1_err) {

  if (ar1_err == null) {
    var preparedStatement = ar1;

    // Create a query : bind parameters
    var query = preparedStatement.createQuery();

    // Get at most 100 rows
    query.fetch(100);

    // Execute query
    query.execute(function (res, res_err) {
      if (res_err == null) {

        // Get result
        var result = res;

        // Close the query
        query.close();
      } else {
        console.log("Query failed " + res_err);
      }
    });
  } else {
    console.log("Could not prepare statement " + ar1_err);
  }
});

----

Prepared statements can also be used for update operations

[source,js]
----
var Tuple = require("vertx-pg-client-js/tuple");

// Prepare (when not cached)
// Execute
conn.preparedQuery("UPDATE USERS SET name=$1 WHERE id=$2", Tuple.of(2, "EMAD ALBLUESHI"), function (ar, ar_err) {

  if (ar_err == null) {
    // Process results
    var result = ar;
  } else {
    console.log("Update failed " + ar_err);
  }
});

----


Prepared statements can also be used to createBatch operations in a very efficient manner:

[source,js]
----
var Tuple = require("vertx-pg-client-js/tuple");
conn.prepare("INSERT INTO USERS (id, name) VALUES ($1, $2)", function (ar1, ar1_err) {
  if (ar1_err == null) {
    var preparedStatement = ar1;

    // Create a query : bind parameters
    var batch = preparedStatement.createBatch();

    // Add commands to the createBatch
    batch.add(Tuple.of("julien", "Julien Viet"));
    batch.add(Tuple.of("emad", "Emad Alblueshi"));

    batch.execute(function (res, res_err) {
      if (res_err == null) {

        // Process results
        var results = res;
      } else {
        console.log("Batch failed " + res_err);
      }
    });
  } else {
    console.log("Could not prepare statement " + ar1_err);
  }
});

----

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../../jsdoc/module-vertx-pg-client-js_pg_client-PgClient.html[PgClient]`
like a Vert.x `NetClient`.

[source,js]
----
var PgClient = require("vertx-pg-client-js/pg_client");

var client = PgClient.create(vertx, {
  "port" : 5432,
  "host" : "the-host",
  "database" : "the-db",
  "username" : "user",
  "password" : "secret",
  "ssl" : true,
  "pemTrustOptions" : {
    "certPaths" : [
      "/path/to/cert.pem"
    ]
  }
});

client.connect(function (res, res_err) {
  if (res_err == null) {
    // Connected with SSL
  } else {
    console.log("Could not connect " + res_err);
  }
});

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].