= Postgres Client for Eclipse Vert.x

== Using the client

To use Postgres Client for Vert.x add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>vertx-pg-client</artifactId>
  <version>0.3.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:vertx-pg-client:0.3.1-SNAPSHOT'
}
----

== Connecting to a database

You can use the client to connect to the database and interact with it.

[source,java]
----
PgClient client = PgClient.create(vertx, new PgClientOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUsername("user")
  .setPassword("secret")
);

client.connect(res -> {
  if (res.succeeded()) {

    // Connected
    PgConnection conn = res.result();

    conn.query("SELECT * FROM USERS", ar -> {

      if (ar.succeeded()) {

        // Use result set
        ResultSet rs = ar.result();
      } else {
        System.out.println("It failed");
      }

      // Close the connection
      conn.close();
    });
  } else {
    System.out.println("Could not connect " + res.cause());
  }
});
----

You can create a pool of connection to obtain a connection instead:

[source,java]
----
PgClient client = PgClient.create(vertx, new PgClientOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUsername("user")
  .setPassword("secret")
);

PgPool pool = client.createPool(new PgPoolOptions().setMaxSize(20));

pool.getConnection(res -> {
  if (res.succeeded()) {

    // Obtained a connection
    PgConnection conn = res.result();

    conn.query("SELECT * FROM USERS", ar -> {

      if (ar.succeeded()) {

        // Use result set
        ResultSet rs = ar.result();
      } else {
        System.out.println("It failed");
      }

      // Return the connection to the pool
      conn.close();
    });
  } else {
    System.out.println("Could not obtain a connection " + res.cause());
  }
});
----

When you are done with the pool, you should close it:

[source,java]
----
pool.close();
----

== Prepared statements

Prepared statements can be created and managed by the application.

The `sql` string can refer to parameters by position, using $1, $2, etc...

[source,java]
----
PgPreparedStatement preparedStatement = conn.prepare("SELECT * FROM USERS WHERE user_id=$1");

// Create a query : bind parameters
PgQuery query = preparedStatement.query("julien");

// Execute query
query.execute(res -> {
  if (res.succeeded()) {

    // Get result
    ResultSet result = res.result();
  } else {
    System.out.println("Query failed " + res.cause());
  }
});
----

When you are done with the prepared statement, you should close it:

[source,java]
----
preparedStatement.close();
----

NOTE: when you close the connection, you don't need to close its prepared statements

By default the query will fetch all results, you can override this and define a maximum fetch size.

[source,java]
----
PgPreparedStatement preparedStatement = conn.prepare("SELECT * FROM USERS");

// Create a query : bind parameters
PgQuery query = preparedStatement.query();

// Get at most 100 rows
query.fetch(100);

// Execute query
query.execute(res -> {
  if (res.succeeded()) {

    // Get result
    ResultSet result = res.result();

    //
    if (query.completed()) {
      // We are done
    } else {

      // Fetch 100 more
      query.execute(res2 -> {
        // And the beat goes on...
      });
    }
  } else {
    System.out.println("Query failed " + res.cause());
  }
});
----

When a query is not completed you can call `link:../../apidocs/com/julienviet/pgclient/PgQuery.html#close--[close]` to release
the query result in progress:

[source,java]
----
PgPreparedStatement preparedStatement = conn.prepare("SELECT * FROM USERS");

// Create a query : bind parameters
PgQuery query = preparedStatement.query();

// Get at most 100 rows
query.fetch(100);

// Execute query
query.execute(res -> {
  if (res.succeeded()) {

    // Get result
    ResultSet result = res.result();

    // Close the query
    query.close();
  } else {
    System.out.println("Query failed " + res.cause());
  }
});
----

Prepared statements can also be used for update operations

[source,java]
----
PgPreparedStatement preparedStatement = conn.prepare("UPDATE USERS SET name=$1 WHERE id=$2");

// Create an update : bind parameters
PgUpdate update = preparedStatement.update(2, "EMAD ALBLUESHI");

update.execute(res -> {
  if(res.succeeded()) {
    // Process results
    UpdateResult result = res.result();
  } else {
    System.out.println("Update failed " + res.cause());
  }

});

// Or fluently
preparedStatement.update(1, "JULIEN VIET").execute(res -> {
  if(res.succeeded()) {
    // Process results
    UpdateResult result = res.result();
  } else {
    System.out.println("Update failed " + res.cause());
  }

});
----


Prepared statements can also be used to batch operations in a very efficient manner:

[source,java]
----
PgPreparedStatement preparedStatement = conn.prepare("INSERT INTO USERS (id, name) VALUES ($1, $2)");

// Create a query : bind parameters
PgBatch batch = preparedStatement.batch();

// Add commands to the batch
batch.add("julien", "Julien Viet");
batch.add("emad", "Emad Alblueshi");

batch.execute(res -> {
  if (res.succeeded()) {

    // Process results
    List<UpdateResult> results = res.result();
  } else {
    System.out.println("Batch failed " + res.cause());
  }
});
----

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../../apidocs/com/julienviet/pgclient/PgClient.html[PgClient]`
like a Vert.x `NetClient`.

[source,java]
----
PgClient client = PgClient.create(vertx, new PgClientOptions()
  .setPort(5432)
  .setHost("the-host")
  .setDatabase("the-db")
  .setUsername("user")
  .setPassword("secret")
  .setSsl(true)
  .setPemTrustOptions(new PemTrustOptions().addCertPath("/path/to/cert.pem"))
);

client.connect(res -> {
  if (res.succeeded()) {
    // Connected with SSL
  } else {
    System.out.println("Could not connect " + res.cause());
  }
});
----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].