=== Server load balancing

You can configure the pool with a list of servers instead of a single server.

[source,$lang]
----
{@link examples.SqlClientExamples#poolConfig01}
----

The pool uses a round-robin load balancing when a connection is created to select different servers.

NOTE: this provides load balancing when the connection is created and not when the connection is borrowed from the pool.

=== Pool connection initialization

You can use the {@link io.vertx.sqlclient.Pool#connectHandler} to interact with a connection after it
has been created and before it is inserted in the pool.

[source,$lang]
----
{@link examples.SqlClientExamples#poolConfig02}
----

Once you are done with the connection, you should simply close it to signal the pool to use it.

=== Dynamic connection provider

By default, the pool create connections using {@link io.vertx.sqlclient.spi.ConnectionFactory#connect ConnectionFactory#connect}.

But you can provide your own implementation in {@link io.vertx.sqlclient.Pool#connectionProvider Pool#connectionProvider}.

Since the provider is asynchronous, it can be used to provide dynamic pool configuration (e.g. password rotation).

[source,$lang]
----
{@link examples.SqlClientExamples#dynamicPoolConfig}
----

CAUTION: When the connection factory becomes useless (e.g. because of a new configuration) it must be closed to release its resources.
