package io.vertx.sqlclient;

import io.vertx.codegen.annotations.DataObject;

/**
 * Options for configuring a query
 */
@DataObject(generateConverter = true)
public class QueryOptions {
	
	private boolean autoGeneratedKeys;
	private boolean locked;

	public QueryOptions() {
	}

	public QueryOptions(QueryOptions other) {
		this.autoGeneratedKeys = other.autoGeneratedKeys;
	}
	
	/**
	 * @return True if auto-generated keys will be returned from any update queries.
	 */
	public boolean getAutoGeneratedKeys() {
		return autoGeneratedKeys;
	}
	
	/**
	 * Set whether or not auto-generated keys should be returned from queries that insert
	 * or update data into rows that have columns with auto-generated keys.
	 * 
	 * @param autoGeneratedKeys True if auto-generated keys should be returned from
	 * queries. False otherwise. The default value is false.
	 * @return a reference to this, so the API can be used fluently
	 */
	public QueryOptions setAutoGeneratedKeys(boolean autoGeneratedKeys) {
		requireUnlocked();
		this.autoGeneratedKeys = autoGeneratedKeys;
		return this;
	}
	
	/**
	 * Locks this instance to prevent further modifications. This method may be called
	 * directly by an application, otherwise it will be called by an implementation once 
	 * the options are first used in a query.
	 * @return a reference to this, so the API can be used fluently
	 */
	public QueryOptions lock() {
		this.locked = true;
		return this;
	}
	
	private void requireUnlocked() {
		if (locked)
			throw new IllegalStateException("An attempt was made to modify a locked instance of QueryOptions");
	}

}
