= Reactive Postgres Client

== Usage

To use the Reactive Postgres Client add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>reactive-pg-client</artifactId>
  <version>0.3.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:reactive-pg-client:0.3.1-SNAPSHOT'
}
----

== Getting started

Here is the simplest way to connect, query and disconnect

[source,kotlin]
----

// Pool options
var options = PgPoolOptions(
  port = 5432,
  host = "the-host",
  database = "the-db",
  username = "user",
  password = "secret",
  maxSize = 5)

// Create the pool
var pool = PgPool.pool(options)

// A simple query
pool.query("SELECT * FROM users WHERE id='julien'", { ar ->
  if (ar.succeeded()) {
    var result = ar.result()
    println("Got ${result.size()} results ")
  } else {
    println("Failure: ${ar.cause().getMessage()}")
  }

  // Close now the pool
  pool.close()
})

----

== Connecting to Postgres

Most of the time you will use a pool to connect to Postgres:

[source,kotlin]
----

// Pool options
var options = PgPoolOptions(
  port = 5432,
  host = "the-host",
  database = "the-db",
  username = "user",
  password = "secret",
  maxSize = 5)

// Create the pool
var pool = PgPool.pool(options)

----

If you are running with Vert.x you can pass it your Vertx instance:

[source,kotlin]
----

// Pool options
var options = PgPoolOptions(
  port = 5432,
  host = "the-host",
  database = "the-db",
  username = "user",
  password = "secret",
  maxSize = 5)

// Create the pool
var pool = PgPool.pool(vertx, options)

----

You need to release the pool when you don't need it anymore:

[source,kotlin]
----

// Close the pool and all the associated resources
pool.close()

----

You can also connect directly to Postgres without a pool

[source,kotlin]
----

// Pool options
var options = PgConnectOptions(
  port = 5432,
  host = "the-host",
  database = "the-db",
  username = "user",
  password = "secret")

// Close the pool and all the associated resources
PgConnection.connect(vertx, options, { res ->
  if (res.succeeded()) {

    println("Connected")

    // Obtain our connection
    var conn = res.result()
  } else {
    println("Could not connect: ${res.cause().getMessage()}")
  }
})

----

== Running queries

When you don't need a transaction or run single queries, you can run queries directly on the pool; the pool
will use one of its connection to run the query and return the result to you.

Here is how to run simple queries:

[source,kotlin]
----
pool.query("SELECT * FROM users WHERE id='julien'", { ar ->
  if (ar.succeeded()) {
    var result = ar.result()
    println("Got ${result.size()} results ")
  } else {
    println("Failure: ${ar.cause().getMessage()}")
  }
})

----

You can do the same with prepared queries.

The sql string can refer to parameters by position, using `$1`, `$2`, etc…​

[source,kotlin]
----
pool.preparedQuery("SELECT * FROM users WHERE id=\$$1", Tuple.of("julien"), { ar ->
  if (ar.succeeded()) {
    var result = ar.result()
    println("Got ${result.size()} results ")
  } else {
    println("Failure: ${ar.cause().getMessage()}")
  }
})

----

Query methods return a `link:../../apidocs/com/julienviet/pgclient/PgResult.html[PgResult]` instance that works for _select_ statements

[source,kotlin]
----
pool.preparedQuery("SELECT first_name, last_name FROM users", { ar ->
  if (ar.succeeded()) {
    var result = ar.result()
    for (row in result) {
      println("User ${row.getString(0)} ${row.getString(1)}")
    }
  } else {
    println("Failure: ${ar.cause().getMessage()}")
  }
})

----

or _update_/_insert_ statements:

[source,kotlin]
----
pool.preparedQuery("\"INSERT INTO users (first_name, last_name) VALUES (\$$1, \$$2)", Tuple.of("Julien", "Viet"), { ar ->
  if (ar.succeeded()) {
    var result = ar.result()
    println(result.updatedCount())
  } else {
    println("Failure: ${ar.cause().getMessage()}")
  }
})

----

The `link:../../apidocs/com/julienviet/pgclient/Row.html[Row]` gives you access to your data by index

[source,kotlin]
----
println("User ${row.getString(0)} ${row.getString(1)}")

----

or by name

[source,kotlin]
----
println("User ${row.getString("first_name")} ${row.getString("last_name")}")

----

You can access a wide variety of of types

[source,kotlin]
----

var firstName = row.getString("first_name")
var male = row.getBoolean("male")
var age = row.getInteger("age")

// ...


----

You can execute prepared batch

[source,kotlin]
----

// Add commands to the batch
var batch = mutableListOf<Any?>()
batch.add(Tuple.of("julien", "Julien Viet"))
batch.add(Tuple.of("emad", "Emad Alblueshi"))

// Execute the prepared batch
connection.preparedBatch("INSERT INTO USERS (id, name) VALUES (\$$1, \$$2)", batch, { res ->
  if (res.succeeded()) {

    // Process results
    var results = res.result()
  } else {
    println("Batch failed ${res.cause()}")
  }
})

----

You can cache prepared statements:

[source,kotlin]
----

// Enable prepare statements
options.cachePreparedStatements = true

var pool = PgPool.pool(vertx, options)

----

== Using connections

When you need to execute sequential queries (without a transaction), you can create a new connection
or borrow one from the pool:

[source,kotlin]
----
Code not translatable
----

Prepared queries can be managed:

[source,kotlin]
----
connection.prepare("SELECT * FROM users WHERE first_name LIKE \$$1", { ar1 ->
  if (ar1.succeeded()) {
    var pq = ar1.result()
    var query = pq.createQuery(Tuple.of("julien"))
    query.execute({ ar2 ->
      if (ar2.succeeded()) {
        // All rows
        var result = ar2.result()
      }
    })
  }
})

----

NOTE: prepared query caching depends on the `link:../../apidocs/com/julienviet/pgclient/PgConnectOptions.html#setCachePreparedStatements-boolean-[setCachePreparedStatements]` and
does not depend on whether you are creating prepared statement or use `link:../../apidocs/com/julienviet/pgclient/PgClient.html#preparedQuery-java.lang.String-io.vertx.core.Handler-[direct prepared queries]`

By default the query will fetch all results, you can override this and define a maximum fetch size using cursors:

[source,kotlin]
----
connection.prepare("SELECT * FROM users WHERE first_name LIKE \$$1", { ar1 ->
  if (ar1.succeeded()) {
    var pq = ar1.result()
    var query = pq.createQuery(Tuple.of("julien")).fetch(50)
    query.execute({ ar2 ->
      if (ar2.succeeded()) {
        var result = ar2.result()

        // Check for more ?
        if (query.hasMore()) {
          query.execute({ ar3 ->
            // More results, and so on...
          })
        } else {
          // No more results
        }
      }
    })
  }
})

----

Cursors shall be closed when they are released prematurely:

[source,kotlin]
----
connection.prepare("SELECT * FROM users WHERE first_name LIKE \$$1", { ar1 ->
  if (ar1.succeeded()) {
    var pq = ar1.result()
    var query = pq.createQuery(Tuple.of("julien")).fetch(50)
    query.execute({ ar2 ->
      if (ar2.succeeded()) {
        // Close the cursor
        query.close()
      }
    })
  }
})

----

A stream API is also available for cursors:

[source,kotlin]
----
connection.prepare("SELECT * FROM users WHERE first_name LIKE \$$1", { ar1 ->
  if (ar1.succeeded()) {
    var pq = ar1.result()

    // Fetch 50 rows at a time
    var stream = pq.createStream(50, Tuple.of("julien"))

    // Use the stream
    stream.exceptionHandler({ err ->
      println("Error: ${err.getMessage()}")
    })
    stream.endHandler({ v ->
      println("End of stream")
    })
    stream.handler({ row ->
      println("User: ${row.getString("last_name")}")
    })
  }
})

----

The stream fetches the rows by batch of `50` and stream them, when the rows have been passed to the handler,
a new batch of `50` is loaded and so on.

The stream can be resumed or paused, the loaded rows will remain in memory until they are delivered and the cursor
will stop iterating.

You can also use `link:../../apidocs/com/julienviet/pgclient/PgPreparedStatement.html[PgPreparedStatement]` for efficient batching:

[source,kotlin]
----
connection.prepare("INSERT INTO USERS (id, name) VALUES (\$$1, \$$2)", { ar1 ->
  if (ar1.succeeded()) {
    var preparedStatement = ar1.result()

    // Create a query : bind parameters
    var batch = preparedStatement.createBatch()

    // Add commands to the createBatch
    batch.add(Tuple.of("julien", "Julien Viet"))
    batch.add(Tuple.of("emad", "Emad Alblueshi"))

    batch.execute({ res ->
      if (res.succeeded()) {

        // Process results
        var results = res.result()
      } else {
        println("Batch failed ${res.cause()}")
      }
    })
  }
})

----

== Using transactions

You can execute transaction using SQL `BEGIN`/`COMMIT`/`ROLLBACK`, if you do so you must use
a `link:../../apidocs/com/julienviet/pgclient/PgConnection.html[PgConnection]` and manage it yourself.

Or you can use the transaction API of `link:../../apidocs/com/julienviet/pgclient/PgConnection.html[PgConnection]`:

[source,kotlin]
----
Code not translatable
----

When Postgres reports the current transaction is failed (e.g the infamous _current transaction is aborted, commands ignored until
end of transaction block_), the transaction is rollbacked and the `link:../../apidocs/com/julienviet/pgclient/PgTransaction.html#abortHandler-io.vertx.core.Handler-[abortHandler]`
is called:

[source,kotlin]
----
pool.connect({ res ->
  if (res.succeeded()) {

    // Transaction must use a connection
    var conn = res.result()

    // Begin the transaction
    var tx = conn.begin().abortHandler({ v ->
      println("Transaction failed => rollbacked")
    })

    conn.query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')", { ar ->
      // Works fine of course
    })
    conn.query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')", { ar ->
      // Fails and triggers transaction aborts
    })

    // Attempt to commit the transaction
    tx.commit({ ar ->
      // But transaction abortion fails it
    })
  }
})

----

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../../apidocs/com/julienviet/pgclient/PgConnectOptions.html[PgConnectOptions]`
like a Vert.x `NetClient`.

[source,kotlin]
----

var options = PgConnectOptions(
  port = 5432,
  host = "the-host",
  database = "the-db",
  username = "user",
  password = "secret",
  ssl = true,
  pemTrustOptions = PemTrustOptions(
    certPaths = listOf("/path/to/cert.pem")))

PgConnection.connect(vertx, options, { res ->
  if (res.succeeded()) {
    // Connected with SSL
  } else {
    println("Could not connect ${res.cause()}")
  }
})

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].