= The Reactive MySQL Client

Documentation:

- https://vertx.io/docs/vertx-mysql-client/java/[Java documentation]
- https://vertx.io/docs/vertx-mysql-client/kotlin/[Kotlin documentation]
- https://vertx.io/docs/vertx-mysql-client/js/[JavaScript documentation]
- https://vertx.io/docs/vertx-mysql-client/groovy/[Groovy documentation]
- https://vertx.io/docs/vertx-mysql-client/ruby/[Ruby documentation]

== Supports

- Connection management
- Connection pooling
- MySQL Native41 authentication
- Text protocol
- Data type mapping
- Prepared statement
- Cursor
- Multi-statement
- Multi-resultset

== TODO

* [ ] Add support for more authentication methods(caching_sha2_password)
* [ ] Authentication methods switch
* [ ] Transaction management
* [ ] Full data type support
* [ ] Compression
* [ ] Replication Protocol(Binlog)

== Supported Data type

MySQL data types are mapped as below.

- BOOLEAN(j.l.Byte)
- INT1(j.l.Byte)
- INT2(j.l.Short)
- INT3(j.l.Integer)
- INT4(j.l.Integer)
- INT8(j.l.Long)
- FLOAT(j.l.Float)
- DOUBLE(j.l.Double)
- NUMERIC,DECIMAL(i.r.p.data.Numeric)
- CHAR(j.l.String)
- BINARY(i.v.c.b.Buffer)
- VARCHAR(j.l.String)
- VARBINARY(i.v.c.b.Buffer)
- TINYBLOB/BLOB/MEDIUMBLOB/LONGBLOB(i.v.c.b.Buffer)
- TINYTEXT/TEXT/MEDIUMTEXT/LONGTEXT(j.l.String)
- DATE(j.t.LocalDate)
- DATETIME(j.t.LocalDateTime)
- TIME(j.t.Duration)
- TIMESTAMP(j.t.LocalDateTime)
- YEAR(j.l.Short)

these data types are not fully supported yet:

* [ ] Numeric: BIT
* [ ] String: ENUM, SET
* [ ] JSON
* [ ] Spatial data types

== Developers

=== Testing

Out of the box, the test suite runs a Docker container using https://www.testcontainers.org/[TestContainers] by default.

You can change the database type of the server by passing a case-insensitive `testing.mysql.database.server` option like this:

```
> mvn test -Dtesting.mysql.database.server=MySQL
```

The following database servers are supported:

- `MySQL`
- `MariaDB`

If the database server is not specified, then `MySQL` will be used by default.

You can also change the version of the database by passing an optional Docker tag named `testing.mysql.database.version` like this:

```
> mvn test -Dtesting.mysql.database.version=5.6.45
```

If the database version is not specified, then `5.7` will be used by default for MySQL while `10.4` will be used by default for MariaDB.

=== Testing with an external database

You can run tests with an external database:

- the script `docker/mysql/resources/create-mysql.sql` creates the test data

You need to add some properties for testing:


```
> mvn test -Dconnection.uri=mysql://$username:$password@$host:$port/$database
```

- connection.uri: configure the client to connect the specified database

=== Testing with Docker

Run the MySQL container with `docker-compose`:

```
> cd docker/mysql
> docker-compose up --build -V
```

Run tests:

```
> mvn test -Dconnection.uri=mysql://$username:$password@$host:$port/$database
```

