= Postgres Client for Eclipse Vert.x

== Using the client

To use Postgres Client for Vert.x add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>vertx-pg-client</artifactId>
  <version>0.3.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:vertx-pg-client:0.3.1-SNAPSHOT'
}
----

== Connecting to a database

You can use the client to connect to the database and interact with it.

[source,groovy]
----

def client = PgClient.create(vertx, [
  port:5432,
  host:"the-host",
  database:"the-db",
  username:"user",
  password:"secret"
])

client.connect({ res ->
  if (res.succeeded()) {

    // Connected
    def conn = res.result()

    conn.query("SELECT * FROM USERS").execute({ ar ->

      if (ar.succeeded()) {

        // Use result
        def result = ar.result()
      } else {
        println("It failed")
      }

      // Close the connection
      conn.close()
    })
  } else {
    println("Could not connect ${res.cause()}")
  }
})

----

You can create a pool of connection to obtain a connection instead:

[source,groovy]
----

def client = PgClient.create(vertx, [
  port:5432,
  host:"the-host",
  database:"the-db",
  username:"user",
  password:"secret"
])

def pool = client.createPool([
  maxSize:20
])

pool.getConnection({ res ->
  if (res.succeeded()) {

    // Obtained a connection
    def conn = res.result()

    conn.query("SELECT * FROM USERS").execute({ ar ->

      if (ar.succeeded()) {

        // Use result set
        def result = ar.result()
      } else {
        println("It failed")
      }

      // Return the connection to the pool
      conn.close()
    })
  } else {
    println("Could not obtain a connection ${res.cause()}")
  }
})

----

When you are done with the pool, you should close it:

[source,groovy]
----

// Close the pool and the connection it maintains
pool.close()

----

== Prepared statements

Prepared statements can be created and managed by the application.

The `sql` string can refer to parameters by position, using $1, $2, etc...

[source,groovy]
----
conn.prepare("SELECT * FROM USERS WHERE user_id=$1", { ar1 ->

  if (ar1.succeeded()) {
    def preparedStatement = ar1.result()

    // Create a query : bind parameters
    def query = preparedStatement.query(Tuple.of("julien"))

    // Execute query
    query.execute({ ar2 ->
      if (ar2.succeeded()) {

        // Get result
        def result = ar2.result()
      } else {
        println("Query failed ${ar2.cause()}")
      }
    })
  } else {
    println("Could not prepare statement ${ar1.cause()}")
  }
})

----

When you are done with the prepared statement, you should close it:

[source,groovy]
----
preparedStatement.close()

----

NOTE: when you close the connection, you don't need to close its prepared statements

By default the query will fetch all results, you can override this and define a maximum fetch size.

[source,groovy]
----
conn.prepare("SELECT * FROM USERS", { ar1 ->
  if (ar1.succeeded()) {

    def preparedStatement = ar1.result()

    // Create a query : bind parameters
    def query = preparedStatement.query().fetch(100)

    query.execute({ ar2 ->

      if (ar2.succeeded()) {
        println("Got at most 100 rows")

        if (query.hasNext()) {
          // Get results
          def result = ar2.result()

          println("Get next 100")
          query.next({ ar3 ->
            // Continue...
          })
        } else {
          // We are done
        }
      } else {
        println("Query failed ${ar2.cause()}")
      }
    })
  } else {
    println("Could not prepare statement ${ar1.cause()}")
  }
})

----

When a query is not completed you can call `link:../../apidocs/com/julienviet/pgclient/PgQuery.html#close--[close]` to release
the query result in progress:

[source,groovy]
----
conn.prepare("SELECT * FROM USERS", { ar1 ->

  if (ar1.succeeded()) {
    def preparedStatement = ar1.result()

    // Create a query : bind parameters
    def query = preparedStatement.query()

    // Get at most 100 rows
    query.fetch(100)

    // Execute query
    query.execute({ res ->
      if (res.succeeded()) {

        // Get result
        def result = res.result()

        // Close the query
        query.close()
      } else {
        println("Query failed ${res.cause()}")
      }
    })
  } else {
    println("Could not prepare statement ${ar1.cause()}")
  }
})

----

Prepared statements can also be used for update operations

[source,groovy]
----

// Prepare (when not cached)
// Execute
conn.preparedQuery("UPDATE USERS SET name=$1 WHERE id=$2", Tuple.of(2, "EMAD ALBLUESHI"), { ar ->

  if (ar.succeeded()) {
    // Process results
    def result = ar.result()
  } else {
    println("Update failed ${ar.cause()}")
  }
})

----


Prepared statements can also be used to batch operations in a very efficient manner:

[source,groovy]
----
conn.prepare("INSERT INTO USERS (id, name) VALUES ($1, $2)", { ar1 ->
  if (ar1.succeeded()) {
    def preparedStatement = ar1.result()

    // Create a query : bind parameters
    def batch = preparedStatement.batch()

    // Add commands to the batch
    batch.add(Tuple.of("julien", "Julien Viet"))
    batch.add(Tuple.of("emad", "Emad Alblueshi"))

    batch.execute({ res ->
      if (res.succeeded()) {

        // Process results
        def results = res.result()
      } else {
        println("Batch failed ${res.cause()}")
      }
    })
  } else {
    println("Could not prepare statement ${ar1.cause()}")
  }
})

----

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../../apidocs/com/julienviet/pgclient/PgClient.html[PgClient]`
like a Vert.x `NetClient`.

[source,groovy]
----

def client = PgClient.create(vertx, [
  port:5432,
  host:"the-host",
  database:"the-db",
  username:"user",
  password:"secret",
  ssl:true,
  pemTrustOptions:[
    certPaths:[
      "/path/to/cert.pem"
    ]
  ]
])

client.connect({ res ->
  if (res.succeeded()) {
    // Connected with SSL
  } else {
    println("Could not connect ${res.cause()}")
  }
})

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].