= Postgres Client for Eclipse Vert.x

== Using the client

To use Postgres Client for Vert.x add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>vertx-pg-client</artifactId>
  <version>0.3.0</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:vertx-pg-client:0.3.0'
}
----

== Connecting to a database

You can use the client to connect to the database and interact with it.

[source,groovy]
----

def client = PgClient.create(vertx, [
  port:5432,
  host:"the-host",
  database:"the-db",
  username:"user",
  password:"secret"
])

client.connect({ res ->
  if (res.succeeded()) {

    // Connected
    def conn = res.result()

    conn.query("SELECT * FROM USERS", { ar ->

      if (ar.succeeded()) {

        // Use result set
        def rs = ar.result()
      } else {
        println("It failed")
      }

      // Close the connection
      conn.close()
    })
  } else {
    println("Could not connect ${res.cause()}")
  }
})

----

You can create a pool of connection to obtain a connection instead:

[source,groovy]
----

def client = PgClient.create(vertx, [
  port:5432,
  host:"the-host",
  database:"the-db",
  username:"user",
  password:"secret"
])

def pool = client.createPool([
  maxSize:20
])

pool.getConnection({ res ->
  if (res.succeeded()) {

    // Obtained a connection
    def conn = res.result()

    conn.query("SELECT * FROM USERS", { ar ->

      if (ar.succeeded()) {

        // Use result set
        def rs = ar.result()
      } else {
        println("It failed")
      }

      // Return the connection to the pool
      conn.close()
    })
  } else {
    println("Could not obtain a connection ${res.cause()}")
  }
})

----

When you are done with the pool, you should close it:

[source,groovy]
----

// Close the pool and the connection it maintains
pool.close()

----

== Prepared statements

Prepared statements can be created and managed by the application.

The `sql` string can refer to parameters by position, using $1, $2, etc...

[source,groovy]
----
def preparedStatement = conn.prepare("SELECT * FROM USERS WHERE user_id=$1")

// Create a query : bind parameters
def query = preparedStatement.query("julien")

// Execute query
query.execute({ res ->
  if (res.succeeded()) {

    // Get result
    def result = res.result()
  } else {
    println("Query failed ${res.cause()}")
  }
})

----

When you are done with the prepared statement, you should close it:

[source,groovy]
----
preparedStatement.close()

----

NOTE: when you close the connection, you don't need to close its prepared statements

By default the query will fetch all results, you can override this and define a maximum fetch size.

[source,groovy]
----
def preparedStatement = conn.prepare("SELECT * FROM USERS")

// Create a query : bind parameters
def query = preparedStatement.query()

// Get at most 100 rows
query.fetch(100)

// Execute query
query.execute({ res ->
  if (res.succeeded()) {

    // Get result
    def result = res.result()

    //
    if (query.completed()) {
      // We are done
    } else {

      // Fetch 100 more
      query.execute({ res2 ->
        // And the beat goes on...
      })
    }
  } else {
    println("Query failed ${res.cause()}")
  }
})

----

When a query is not completed you can call `link:../../apidocs/com/julienviet/pgclient/PgQuery.html#close--[close]` to release
the query result in progress:

[source,groovy]
----
def preparedStatement = conn.prepare("SELECT * FROM USERS")

// Create a query : bind parameters
def query = preparedStatement.query()

// Get at most 100 rows
query.fetch(100)

// Execute query
query.execute({ res ->
  if (res.succeeded()) {

    // Get result
    def result = res.result()

    // Close the query
    query.close()
  } else {
    println("Query failed ${res.cause()}")
  }
})

----

Prepared statements can also be used to batch operations in a very efficient manner:

[source,groovy]
----
def preparedStatement = conn.prepare("INSERT INTO USERS (id, name) VALUES ($1, $2)")

// Create a query : bind parameters
def batch = preparedStatement.batch()

// Add commands to the batch
batch.add("julien", "Julien Viet")
batch.add("emad", "Emad Alblueshi")

batch.execute({ res ->
  if (res.succeeded()) {

    // Process results
    def results = res.result()
  } else {
    println("Batch failed ${res.cause()}")
  }
})

----