= Postgres Client for Eclipse Vert.x

== Using the client

To use Postgres Client for Vert.x add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>reactive-pg-client</artifactId>
  <version>0.3.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:reactive-pg-client:0.3.1-SNAPSHOT'
}
----

== Connecting to a database

You can use the client to connect to the database and interact with it.

[source,ruby]
----
require 'vertx-pg-client/pg_connection'

# Create options
options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret"
}

# Connect
VertxPgClient::PgConnection.connect(vertx, options) { |res_err,res|
  if (res_err == nil)

    # Connected
    conn = res

    conn.create_query("SELECT * FROM USERS").execute() { |ar_err,ar|

      if (ar_err == nil)

        # Use result
        result = ar
      else
        puts "It failed"
      end

      # Close the connection
      conn.close()
    }
  else
    puts "Could not connect #{res_err}"
  end
}

----

You can create a pool of connection to obtain a connection instead:

[source,ruby]
----
require 'vertx-pg-client/pg_pool'

options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret",
  'maxSize' => 20
}

# Create a pool with 20 connections max
pool = VertxPgClient::PgPool.pool(vertx, options)

pool.connect() { |res_err,res|
  if (res_err == nil)

    # Obtained a connection
    conn = res

    conn.create_query("SELECT * FROM USERS").execute() { |ar_err,ar|

      if (ar_err == nil)

        # Use result set
        result = ar
      else
        puts "It failed"
      end

      # Return the connection to the pool
      conn.close()
    }
  else
    puts "Could not obtain a connection #{res_err}"
  end
}

----

When you are done with the pool, you should close it:

[source,ruby]
----

# Close the pool and the connection it maintains
pool.close()

----

== Prepared statements

Prepared statements can be created and managed by the application.

The `sql` string can refer to parameters by position, using $1, $2, etc...

[source,ruby]
----
require 'vertx-pg-client/tuple'
conn.prepare("SELECT * FROM USERS WHERE user_id=$1") { |ar1_err,ar1|

  if (ar1_err == nil)
    preparedStatement = ar1

    # Create a query : bind parameters
    query = preparedStatement.create_query(VertxPgClient::Tuple.of("julien"))

    # Execute query
    query.execute() { |ar2_err,ar2|
      if (ar2_err == nil)

        # Get result
        result = ar2
      else
        puts "Query failed #{ar2_err}"
      end
    }
  else
    puts "Could not prepare statement #{ar1_err}"
  end
}

----

When you are done with the prepared statement, you should close it:

[source,ruby]
----
preparedStatement.close()

----

NOTE: when you close the connection, you don't need to close its prepared statements

By default the query will fetch all results, you can override this and define a maximum fetch size.

[source,ruby]
----
conn.prepare("SELECT * FROM USERS") { |ar1_err,ar1|
  if (ar1_err == nil)

    preparedStatement = ar1

    # Create a query : bind parameters
    query = preparedStatement.create_query().fetch(100)

    query.execute() { |ar2_err,ar2|

      if (ar2_err == nil)
        puts "Got at most 100 rows"

        if (query.has_more?())
          # Get results
          result = ar2

          puts "Get next 100"
          query.execute() { |ar3_err,ar3|
            # Continue...
          }
        else
          # We are done
        end
      else
        puts "Query failed #{ar2_err}"
      end
    }
  else
    puts "Could not prepare statement #{ar1_err}"
  end
}

----

When a query is not completed you can call `link:../../yardoc/VertxPgClient/PgQuery.html#close-instance_method[close]` to release
the query result in progress:

[source,ruby]
----
conn.prepare("SELECT * FROM USERS") { |ar1_err,ar1|

  if (ar1_err == nil)
    preparedStatement = ar1

    # Create a query : bind parameters
    query = preparedStatement.create_query()

    # Get at most 100 rows
    query.fetch(100)

    # Execute query
    query.execute() { |res_err,res|
      if (res_err == nil)

        # Get result
        result = res

        # Close the query
        query.close()
      else
        puts "Query failed #{res_err}"
      end
    }
  else
    puts "Could not prepare statement #{ar1_err}"
  end
}

----

Prepared statements can also be used for update operations

[source,ruby]
----
require 'vertx-pg-client/tuple'

# Prepare (when not cached)
# Execute
conn.prepared_query("UPDATE USERS SET name=$1 WHERE id=$2", VertxPgClient::Tuple.of(2, "EMAD ALBLUESHI")) { |ar_err,ar|

  if (ar_err == nil)
    # Process results
    result = ar
  else
    puts "Update failed #{ar_err}"
  end
}

----


Prepared statements can also be used to createBatch operations in a very efficient manner:

[source,ruby]
----
require 'vertx-pg-client/tuple'
conn.prepare("INSERT INTO USERS (id, name) VALUES ($1, $2)") { |ar1_err,ar1|
  if (ar1_err == nil)
    preparedStatement = ar1

    # Create a query : bind parameters
    batch = preparedStatement.create_batch()

    # Add commands to the createBatch
    batch.add(VertxPgClient::Tuple.of("julien", "Julien Viet"))
    batch.add(VertxPgClient::Tuple.of("emad", "Emad Alblueshi"))

    batch.execute() { |res_err,res|
      if (res_err == nil)

        # Process results
        results = res
      else
        puts "Batch failed #{res_err}"
      end
    }
  else
    puts "Could not prepare statement #{ar1_err}"
  end
}

----

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../dataobjects.html#PgConnectOptions[PgConnectOptions]`
like a Vert.x `NetClient`.

[source,ruby]
----
require 'vertx-pg-client/pg_connection'

options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret",
  'ssl' => true,
  'pemTrustOptions' => {
    'certPaths' => [
      "/path/to/cert.pem"
    ]
  }
}

VertxPgClient::PgConnection.connect(vertx, options) { |res_err,res|
  if (res_err == nil)
    # Connected with SSL
  else
    puts "Could not connect #{res_err}"
  end
}

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].