= Reactive Postgres Client

== Usage

To use the Reactive Postgres Client add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>com.julienviet</groupId>
  <artifactId>reactive-pg-client</artifactId>
  <version>0.3.1-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
dependencies {
  compile 'com.julienviet:reactive-pg-client:0.3.1-SNAPSHOT'
}
----

== Getting started

Here is the simplest way to connect, query and disconnect

[source,ruby]
----
require 'vertx-pg-client/pg_pool'

# Pool options
options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret",
  'maxSize' => 5
}

# Create the pool
pool = VertxPgClient::PgPool.pool(options)

# A simple query
pool.query("SELECT * FROM users WHERE id='julien'") { |ar_err,ar|
  if (ar_err == nil)
    result = ar
    puts "Got #{result.size()} results "
  else
    puts "Failure: #{ar_err.get_message()}"
  end

  # Close now the pool
  pool.close()
}

----

== Connecting to Postgres

Most of the time you will use a pool to connect to Postgres:

[source,ruby]
----
require 'vertx-pg-client/pg_pool'

# Pool options
options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret",
  'maxSize' => 5
}

# Create the pool
pool = VertxPgClient::PgPool.pool(options)

----

If you are running with Vert.x you can pass it your Vertx instance:

[source,ruby]
----
require 'vertx-pg-client/pg_pool'

# Pool options
options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret",
  'maxSize' => 5
}

# Create the pool
pool = VertxPgClient::PgPool.pool(vertx, options)

----

You need to release the pool when you don't need it anymore:

[source,ruby]
----

# Close the pool and all the associated resources
pool.close()

----

You can also connect directly to Postgres without a pool

[source,ruby]
----
require 'vertx-pg-client/pg_connection'

# Pool options
options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret"
}

# Close the pool and all the associated resources
VertxPgClient::PgConnection.connect(vertx, options) { |res_err,res|
  if (res_err == nil)

    puts "Connected"

    # Obtain our connection
    conn = res
  else
    puts "Could not connect: #{res_err.get_message()}"
  end
}

----

== Running queries

When you don't need a transaction or run single queries, you can run queries directly on the pool; the pool
will use one of its connection to run the query and return the result to you.

Here is how to run simple queries:

[source,ruby]
----
pool.query("SELECT * FROM users WHERE id='julien'") { |ar_err,ar|
  if (ar_err == nil)
    result = ar
    puts "Got #{result.size()} results "
  else
    puts "Failure: #{ar_err.get_message()}"
  end
}

----

You can do the same with prepared queries.

The sql string can refer to parameters by position, using `$1`, `$2`, etc…​

[source,ruby]
----
require 'vertx-pg-client/tuple'
pool.prepared_query("SELECT * FROM users WHERE id=$1", VertxPgClient::Tuple.of("julien")) { |ar_err,ar|
  if (ar_err == nil)
    result = ar
    puts "Got #{result.size()} results "
  else
    puts "Failure: #{ar_err.get_message()}"
  end
}

----

Query methods return a `link:../../yardoc/VertxPgClient/PgResult.html[PgResult]` instance that works for _select_ statements

[source,ruby]
----
pool.prepared_query("SELECT first_name, last_name FROM users") { |ar_err,ar|
  if (ar_err == nil)
    result = ar
    result.each do |row|
      puts "User #{row.get_string(0)} #{row.get_string(1)}"
    end
  else
    puts "Failure: #{ar_err.get_message()}"
  end
}

----

or _update_/_insert_ statements:

[source,ruby]
----
require 'vertx-pg-client/tuple'
pool.prepared_query("\"INSERT INTO users (first_name, last_name) VALUES ($1, $2)", VertxPgClient::Tuple.of("Julien", "Viet")) { |ar_err,ar|
  if (ar_err == nil)
    result = ar
    puts result.updated_count()
  else
    puts "Failure: #{ar_err.get_message()}"
  end
}

----

The `link:../../yardoc/VertxPgClient/Row.html[Row]` gives you access to your data by index

[source,ruby]
----
puts "User #{row.get_string(0)} #{row.get_string(1)}"

----

or by name

[source,ruby]
----
puts "User #{row.get_string("first_name")} #{row.get_string("last_name")}"

----

You can access a wide variety of of types

[source,ruby]
----

firstName = row.get_string("first_name")
male = row.get_boolean?("male")
age = row.get_integer("age")

# ...


----

You can execute prepared batch

[source,ruby]
----
require 'vertx-pg-client/tuple'

# Add commands to the batch
batch = Array.new
batch.push(VertxPgClient::Tuple.of("julien", "Julien Viet"))
batch.push(VertxPgClient::Tuple.of("emad", "Emad Alblueshi"))

# Execute the prepared batch
connection.prepared_batch("INSERT INTO USERS (id, name) VALUES ($1, $2)", batch) { |res_err,res|
  if (res_err == nil)

    # Process results
    results = res
  else
    puts "Batch failed #{res_err}"
  end
}

----

You can cache prepared statements:

[source,ruby]
----
require 'vertx-pg-client/pg_pool'

# Enable prepare statements
options['cachePreparedStatements'] = true

pool = VertxPgClient::PgPool.pool(vertx, options)

----

== Using connections

When you need to execute sequential queries (without a transaction), you can create a new connection
or borrow one from the pool:

[source,ruby]
----
Code not translatable
----

Prepared queries can be managed:

[source,ruby]
----
require 'vertx-pg-client/tuple'
connection.prepare("SELECT * FROM users WHERE first_name LIKE $1") { |ar1_err,ar1|
  if (ar1_err == nil)
    pq = ar1
    query = pq.create_query(VertxPgClient::Tuple.of("julien"))
    query.execute() { |ar2_err,ar2|
      if (ar2_err == nil)
        # All rows
        result = ar2
      end
    }
  end
}

----

NOTE: prepared query caching depends on the `link:../dataobjects.html#PgConnectOptions#set_cache_prepared_statements-instance_method[cachePreparedStatements]` and
does not depend on whether you are creating prepared statement or use `link:../../yardoc/VertxPgClient/PgClient.html#prepared_query-instance_method[direct prepared queries]`

By default the query will fetch all results, you can override this and define a maximum fetch size using cursors:

[source,ruby]
----
require 'vertx-pg-client/tuple'
connection.prepare("SELECT * FROM users WHERE first_name LIKE $1") { |ar1_err,ar1|
  if (ar1_err == nil)
    pq = ar1
    query = pq.create_query(VertxPgClient::Tuple.of("julien")).fetch(50)
    query.execute() { |ar2_err,ar2|
      if (ar2_err == nil)
        result = ar2

        # Check for more ?
        if (query.has_more?())
          query.execute() { |ar3_err,ar3|
            # More results, and so on...
          }
        else
          # No more results
        end
      end
    }
  end
}

----

Cursors shall be closed when they are released prematurely:

[source,ruby]
----
require 'vertx-pg-client/tuple'
connection.prepare("SELECT * FROM users WHERE first_name LIKE $1") { |ar1_err,ar1|
  if (ar1_err == nil)
    pq = ar1
    query = pq.create_query(VertxPgClient::Tuple.of("julien")).fetch(50)
    query.execute() { |ar2_err,ar2|
      if (ar2_err == nil)
        # Close the cursor
        query.close()
      end
    }
  end
}

----

A stream API is also available for cursors:

[source,ruby]
----
require 'vertx-pg-client/tuple'
connection.prepare("SELECT * FROM users WHERE first_name LIKE $1") { |ar1_err,ar1|
  if (ar1_err == nil)
    pq = ar1

    # Fetch 50 rows at a time
    stream = pq.create_stream(50, VertxPgClient::Tuple.of("julien"))

    # Use the stream
    stream.exception_handler() { |err|
      puts "Error: #{err.get_message()}"
    }
    stream.end_handler() { |v|
      puts "End of stream"
    }
    stream.handler() { |row|
      puts "User: #{row.get_string("last_name")}"
    }
  end
}

----

The stream fetches the rows by batch of `50` and stream them, when the rows have been passed to the handler,
a new batch of `50` is loaded and so on.

The stream can be resumed or paused, the loaded rows will remain in memory until they are delivered and the cursor
will stop iterating.

You can also use `link:../../yardoc/VertxPgClient/PgPreparedStatement.html[PgPreparedStatement]` for efficient batching:

[source,ruby]
----
require 'vertx-pg-client/tuple'
connection.prepare("INSERT INTO USERS (id, name) VALUES ($1, $2)") { |ar1_err,ar1|
  if (ar1_err == nil)
    preparedStatement = ar1

    # Create a query : bind parameters
    batch = preparedStatement.create_batch()

    # Add commands to the createBatch
    batch.add(VertxPgClient::Tuple.of("julien", "Julien Viet"))
    batch.add(VertxPgClient::Tuple.of("emad", "Emad Alblueshi"))

    batch.execute() { |res_err,res|
      if (res_err == nil)

        # Process results
        results = res
      else
        puts "Batch failed #{res_err}"
      end
    }
  end
}

----

== Using transactions

You can execute transaction using SQL `BEGIN`/`COMMIT`/`ROLLBACK`, if you do so you must use
a `link:../../yardoc/VertxPgClient/PgConnection.html[PgConnection]` and manage it yourself.

Or you can use the transaction API of `link:../../yardoc/VertxPgClient/PgConnection.html[PgConnection]`:

[source,ruby]
----
Code not translatable
----

When Postgres reports the current transaction is failed (e.g the infamous _current transaction is aborted, commands ignored until
end of transaction block_), the transaction is rollbacked and the `link:../../yardoc/VertxPgClient/PgTransaction.html#abort_handler-instance_method[abortHandler]`
is called:

[source,ruby]
----
pool.connect() { |res_err,res|
  if (res_err == nil)

    # Transaction must use a connection
    conn = res

    # Begin the transaction
    tx = conn.begin().abort_handler() { |v|
      puts "Transaction failed => rollbacked"
    }

    conn.query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')") { |ar_err,ar|
      # Works fine of course
    }
    conn.query("INSERT INTO Users (first_name,last_name) VALUES ('Julien','Viet')") { |ar_err,ar|
      # Fails and triggers transaction aborts
    }

    # Attempt to commit the transaction
    tx.commit() { |ar_err,ar|
      # But transaction abortion fails it
    }
  end
}

----

== Pub/sub

Postgres supports pub/sub communication channels.

You can set a `link:../../yardoc/VertxPgClient/PgConnection.html#notification_handler-instance_method[notificationHandler]` to receive
Postgres notifications:

[source,ruby]
----

connection.notification_handler() { |notification|
  puts "Received #{notification['payload']} on channel #{notification['channel']}"
}

connection.query("LISTEN some-channel") { |ar_err,ar|
  puts "Subscribed to channel"
}

----

The `link:../../yardoc/VertxPgClient/PgSubscriber.html[PgSubscriber]` is a channel manager managing a single connection that
provides per channel subscription:

[source,ruby]
----
require 'vertx-pg-client/pg_subscriber'

subscriber = VertxPgClient::PgSubscriber.subscriber(vertx, {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret"
})

# You can set the channel before connect
subscriber.channel("channel1").handler() { |payload|
  puts "Received #{payload}"
}

subscriber.connect() { |ar_err,ar|
  if (ar_err == nil)

    # Or you can set the channel after connect
    subscriber.channel("channel2").handler() { |payload|
      puts "Received #{payload}"
    }
  end
}

----

You can provide a reconnect policy as a function that takes the number of `retries` as argument and returns an `amountOfTime`
value:

* when `amountOfTime < 0`: the subscriber is closed and there is no retry
* when `amountOfTime == 0`: the subscriber retries to connect immediately
* when `amountOfTime > 0`: the subscriber retries after `amountOfTime` milliseconds

[source,ruby]
----
require 'vertx-pg-client/pg_subscriber'

subscriber = VertxPgClient::PgSubscriber.subscriber(vertx, {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret"
})

# Reconnect at most 10 times after 100 ms each
subscriber.reconnect_policy(lambda { |retries|
  if (retries < 10)
    return 100
  else
    return -1
  end
})

----

The default policy is to not reconnect.

== Using SSL/TLS

To configure the client to use SSL connection, you can configure the `link:../dataobjects.html#PgConnectOptions[PgConnectOptions]`
like a Vert.x `NetClient`.

[source,ruby]
----
require 'vertx-pg-client/pg_connection'

options = {
  'port' => 5432,
  'host' => "the-host",
  'database' => "the-db",
  'username' => "user",
  'password' => "secret",
  'ssl' => true,
  'pemTrustOptions' => {
    'certPaths' => [
      "/path/to/cert.pem"
    ]
  }
}

VertxPgClient::PgConnection.connect(vertx, options) { |res_err,res|
  if (res_err == nil)
    # Connected with SSL
  else
    puts "Could not connect #{res_err}"
  end
}

----

More information can be found in the http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].

== Using a proxy

You can also configure the client to use an HTTP/1.x CONNECT, SOCKS4a or SOCKS5 proxy.

More information can be found in the http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].