version: "3"

services:
  test-postgres:
    image: healthcheck/postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - ../../src/test/resources/create-postgres.sql:/docker-entrypoint-initdb.d/create-postgres.sql
  tls-test-postgres:
    image: healthcheck/postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../../src/test/resources/create-postgres.sql:/docker-entrypoint-initdb.d/create-postgres.sql
      - ../../src/test/resources/tls/server.crt:/server.crt
      - ../../src/test/resources/tls/server.key:/server.key
      - ../../src/test/resources/tls/ssl.sh:/docker-entrypoint-initdb.d/ssl.sh
