name: vertx-sql-client (4.x)
on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9x]+'
  pull_request:
    branches:
      - master
      - '[0-9]+.[0-9x]+'
  schedule:
    - cron:  '0 4 * * *'
jobs:
  Test:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        include:
          # JDK 8 tests
          - os: ubuntu-latest
            jdk: 8
            profile: 'PostgreSQL-9'
            module: 'vertx-pg-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'PostgreSQL-10'
            module: 'vertx-pg-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'PostgreSQL-11'
            module: 'vertx-pg-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MySQL-8.0'
            module: 'vertx-mysql-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MySQL-5.6'
            module: 'vertx-mysql-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MySQL-5.7'
            module: 'vertx-mysql-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MariaDB-10.4'
            module: 'vertx-mysql-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MSSQL-2017-latest'
            module: 'vertx-mssql-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'MSSQL-2019-latest'
            module: 'vertx-mssql-client'
          - os: ubuntu-latest
            jdk: 8
            profile: 'DB2-11.5'
            module: 'vertx-db2-client'
          - os: ubuntu-latest
            jdk: 8
            module: 'vertx-sql-client-templates'
          # JDK 25 tests (subset)
          - os: ubuntu-latest
            jdk: 25
            profile: 'PostgreSQL-11'
            module: 'vertx-pg-client'
          - os: ubuntu-latest
            jdk: 25
            profile: 'MySQL-5.7'
            module: 'vertx-mysql-client'
          - os: ubuntu-latest
            jdk: 25
            profile: 'MariaDB-10.4'
            module: 'vertx-mysql-client'
          - os: ubuntu-latest
            jdk: 25
            profile: 'MSSQL-2019-latest'
            module: 'vertx-mssql-client'
          - os: ubuntu-latest
            jdk: 25
            profile: 'Oracle-23'
            module: 'vertx-oracle-client'
    runs-on: ${{ matrix.os }}
    env:
      PROFILE_ARG: ${{ matrix.profile && format('-P {0}', matrix.profile) || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin
      - name: Build without tests
        run: |
          mvn -s .github/maven-ci-settings.xml -q clean install -B $PROFILE_ARG -pl :${{ matrix.module }} -am -DskipTests
      - name: Run tests for the target module
        run: |
          mvn -s .github/maven-ci-settings.xml -q verify -B $PROFILE_ARG -pl :${{ matrix.module }}
  Deploy:
    name: Deploy to OSSRH
    if: ${{ github.repository_owner == 'eclipse-vertx' && (github.event_name == 'push' || github.event_name == 'schedule') }}
    needs: Test
    runs-on: ubuntu-latest
    env:
      VERTX_NEXUS_USERNAME: ${{ secrets.VERTX_NEXUS_USERNAME }}
      VERTX_NEXUS_PASSWORD: ${{ secrets.VERTX_NEXUS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
      - name: Get project version
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:evaluate -Dexpression=project.version -B | grep -v '\[')" >> $GITHUB_ENV
      - name: Maven deploy
        if: ${{ endsWith(env.PROJECT_VERSION, '-SNAPSHOT') }}
        run: mvn deploy -s .github/maven-cd-settings.xml -DskipTests -B
