name: CI
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      jdk:
        default: 8
        type: string
      os:
        default: ubuntu-latest
        type: string
      profile:
        type: string
      module:
        required: true
        type: string
      deploy:
        type: boolean
jobs:
  Test:
    name: Run tests
    runs-on: ${{ inputs.os }}
    env:
      PROFILE_ARG: ${{ inputs.profile && format('-P {0}', inputs.profile) || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.branch }}
      - name: Install JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.jdk }}
          distribution: temurin
      - name: Build without tests
        run: |
          mvn -s .github/maven-ci-settings.xml -q clean install -B $PROFILE_ARG -pl :${{ inputs.module }} -am -DskipTests
      - name: Run tests for the target module
        run: |
          mvn -s .github/maven-ci-settings.xml -q verify -B $PROFILE_ARG -pl :${{ inputs.module }}
