name: vertx-sql-client nightly (5.x-stable)
on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  CI-CD:
    uses: ./.github/workflows/ci-matrix-5.x.yml
    secrets: inherit
    with:
      branch: ${{ github.event_name == 'schedule' && vars.VERTX_5_STABLE_BRANCH || github.ref_name }}
