name: vertx-sql-client (5.x)
on:
  schedule:
    - cron: '0 5 * * *'
jobs:
  CI-CD:
    uses: ./.github/workflows/ci-matrix-5.x.yml
    secrets: inherit
    with:
      branch: ${{ github.ref_name }}
